version: '3.8'

services:
  api:
    build: .
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    networks:
      - app-network

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
